"""
Data loader for NFL player statistics
Loads from pre-built CSV file (generated by scripts/download_nfl_data.py)
Uses Polars for data loading to avoid numpy/pandas compatibility issues
"""
import os
from typing import Optional, List
import warnings
warnings.filterwarnings('ignore')

# Use polars for data loading
import polars as pl

import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import (
    SUPER_BOWL_ERA_START, CURRENT_YEAR, NFL_TEAMS, 
    TEAM_NAME_MAPPINGS, STAT_CATEGORIES
)

# Data file path
DATA_DIR = os.path.dirname(__file__)
PLAYER_STATS_FILE = os.path.join(DATA_DIR, 'nfl_player_stats.csv')

# Cache for loaded data
_player_database_cache = None


def normalize_team_abbr(team: str) -> str:
    """Normalize team abbreviation to current team name"""
    if team is None:
        return None
    team = str(team).upper().strip()
    return TEAM_NAME_MAPPINGS.get(team, team)


def load_player_database() -> pl.DataFrame:
    """
    Load the player database from CSV file
    
    Returns:
        Polars DataFrame with player stats
    """
    global _player_database_cache
    
    if _player_database_cache is not None:
        return _player_database_cache
    
    if os.path.exists(PLAYER_STATS_FILE):
        try:
            df = pl.read_csv(PLAYER_STATS_FILE)
            print(f"✓ Loaded player database: {len(df):,} records, {df['player'].n_unique():,} players")
            _player_database_cache = df
            return df
        except Exception as e:
            print(f"⚠ Error loading CSV file: {e}")
    
    # Fallback to sample data if CSV doesn't exist
    print("⚠ Player stats file not found, using sample data")
    print(f"  Expected: {PLAYER_STATS_FILE}")
    print("  Run: python scripts/download_nfl_data.py to generate")
    
    df = create_sample_data()
    _player_database_cache = df
    return df


def create_sample_data() -> pl.DataFrame:
    """
    Create sample data for testing when CSV file is unavailable
    """
    print("Creating sample data for testing...")
    
    sample_data = {
        'player': ['Patrick Mahomes', 'Josh Allen', 'Lamar Jackson', 'Saquon Barkley', 
                   'Derrick Henry', 'Jahmyr Gibbs', "Ja'Marr Chase", 'Nico Collins',
                   'Malik Nabers', 'Brock Bowers', 'Travis Kelce', 'Tom Brady', 'Peyton Manning'],
        'season': [2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2007, 2013],
        'team': ['KC', 'BUF', 'BAL', 'PHI', 'BAL', 'DET', 'CIN', 'HOU', 'NYG', 'LV', 'KC', 'NE', 'DEN'],
        'position': ['QB', 'QB', 'QB', 'RB', 'RB', 'RB', 'WR', 'WR', 'WR', 'TE', 'TE', 'QB', 'QB'],
        'passing_yards': [4183.0, 4306.0, 4172.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4806.0, 5477.0],
        'passing_tds': [27, 29, 41, 0, 0, 0, 0, 0, 0, 0, 0, 50, 55],
        'rushing_yards': [389.0, 524.0, 915.0, 2005.0, 1921.0, 1412.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        'rushing_tds': [0, 15, 4, 13, 16, 16, 0, 0, 0, 0, 0, 0, 0],
        'receiving_yards': [0.0, 0.0, 0.0, 278.0, 214.0, 517.0, 1708.0, 1006.0, 1204.0, 1194.0, 823.0, 0.0, 0.0],
        'receiving_tds': [0, 0, 0, 2, 1, 4, 17, 7, 7, 5, 3, 0, 0],
        'receptions': [0, 0, 0, 33, 28, 52, 127, 60, 109, 112, 97, 0, 0],
        'fantasy_points': [298.5, 380.2, 402.4, 334.3, 319.5, 312.9, 272.8, 142.6, 162.4, 149.4, 100.3, 376.2, 419.1],
        'fantasy_points_ppr': [298.5, 380.2, 402.4, 367.3, 347.5, 364.9, 399.8, 202.6, 271.4, 261.4, 197.3, 376.2, 419.1],
    }
    
    df = pl.DataFrame(sample_data)
    print(f"✓ Created sample data with {len(df)} player-season records")
    return df


def get_player_database(force_refresh: bool = False) -> pl.DataFrame:
    """Get the player database (main entry point)"""
    global _player_database_cache
    
    if force_refresh:
        _player_database_cache = None
    
    return load_player_database()


def get_all_players(df: Optional[pl.DataFrame] = None) -> List[str]:
    """Get list of all unique player names"""
    if df is None:
        df = get_player_database()
    return sorted(df['player'].drop_nulls().unique().to_list())


def search_players(query: str, df: Optional[pl.DataFrame] = None, limit: int = 10) -> List[str]:
    """
    Search for players by name (case-insensitive partial match)
    
    Args:
        query: Search string
        df: Player database (loads if not provided)
        limit: Maximum results to return
        
    Returns:
        List of matching player names
    """
    if df is None:
        df = get_player_database()
    
    if not query or len(query) < 2:
        return []
    
    query_lower = query.lower()
    
    # Get unique players
    players = df['player'].drop_nulls().unique().to_list()
    
    # Find matches (prioritize starts-with, then contains)
    starts_with = [p for p in players if p.lower().startswith(query_lower)]
    contains = [p for p in players if query_lower in p.lower() and p not in starts_with]
    
    matches = starts_with + contains
    return matches[:limit]


def get_player_seasons(player_name: str, df: Optional[pl.DataFrame] = None) -> List[int]:
    """Get all seasons a player has data for"""
    if df is None:
        df = get_player_database()
    
    player_data = df.filter(pl.col('player') == player_name)
    return sorted(player_data['season'].unique().to_list(), reverse=True)


def get_player_stats(player_name: str, season: int, df: Optional[pl.DataFrame] = None) -> Optional[dict]:
    """
    Get a player's stats for a specific season
    
    Returns:
        Dictionary of stats or None if not found
    """
    if df is None:
        df = get_player_database()
    
    player_data = df.filter((pl.col('player') == player_name) & (pl.col('season') == season))
    
    if len(player_data) == 0:
        return None
    
    return player_data.row(0, named=True)


def get_valid_players_for_criteria(
    df: pl.DataFrame,
    stat_category: str,
    team: Optional[str] = None,
    year_start: Optional[int] = None,
    year_end: Optional[int] = None,
    position: Optional[str] = None,
    division: Optional[str] = None,
    conference: Optional[str] = None
) -> pl.DataFrame:
    """
    Filter players that meet the given criteria
    
    Args:
        df: Player database DataFrame
        stat_category: The stat being maximized
        team: Team abbreviation filter
        year_start: Start year filter
        year_end: End year filter
        position: Position filter
        division: Division filter
        conference: Conference filter
        
    Returns:
        Filtered DataFrame of valid players
    """
    filtered = df
    
    # Get stat info
    stat_info = STAT_CATEGORIES.get(stat_category, {})
    stat_col = stat_category
    eligible_positions = stat_info.get('eligible_positions', [])
    
    # Filter by year range
    if year_start is not None:
        filtered = filtered.filter(pl.col('season') >= year_start)
    if year_end is not None:
        filtered = filtered.filter(pl.col('season') <= year_end)
    
    # Filter by team
    if team is not None:
        team = normalize_team_abbr(team)
        filtered = filtered.filter(pl.col('team') == team)
    
    # Filter by position
    if position is not None:
        filtered = filtered.filter(pl.col('position') == position)
    elif eligible_positions:
        filtered = filtered.filter(pl.col('position').is_in(eligible_positions))
    
    # Filter by division
    if division is not None:
        division_teams = [abbr for abbr, info in NFL_TEAMS.items() if info.get('division') == division]
        filtered = filtered.filter(pl.col('team').is_in(division_teams))
    
    # Filter by conference
    if conference is not None:
        conf_teams = [abbr for abbr, info in NFL_TEAMS.items() if info.get('conference') == conference]
        filtered = filtered.filter(pl.col('team').is_in(conf_teams))
    
    # Filter to players who have the stat
    if stat_col in filtered.columns:
        filtered = filtered.filter(pl.col(stat_col).is_not_null() & (pl.col(stat_col) > 0))
    
    return filtered


def get_teams_for_year(year: int, df: Optional[pl.DataFrame] = None) -> List[str]:
    """Get list of teams that have data for a given year"""
    if df is None:
        df = get_player_database()
    
    year_data = df.filter(pl.col('season') == year)
    return sorted(year_data['team'].drop_nulls().unique().to_list())


def get_positions(df: Optional[pl.DataFrame] = None) -> List[str]:
    """Get list of all positions in the database"""
    if df is None:
        df = get_player_database()
    
    return sorted(df['position'].drop_nulls().unique().to_list())


def get_year_range(df: Optional[pl.DataFrame] = None) -> tuple:
    """Get the min and max years in the database"""
    if df is None:
        df = get_player_database()
    
    return int(df['season'].min()), int(df['season'].max())


# Backwards compatibility aliases
build_player_database = get_player_database
load_seasonal_data = get_player_database